Document: vibe2gui
Title: Debian vibe2gui Manual
Author: <insert document author here>
Abstract: This manual describes what vibe2gui is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vibe2gui/vibe2gui.sgml.gz

Format: postscript
Files: /usr/share/doc/vibe2gui/vibe2gui.ps.gz

Format: text
Files: /usr/share/doc/vibe2gui/vibe2gui.text.gz

Format: HTML
Index: /usr/share/doc/vibe2gui/html/index.html
Files: /usr/share/doc/vibe2gui/html/*.html
